version: '3'
services:
# Veritabanı servisi
    db: 
        image: mysql:5.7
        volumes:
            - db_data:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: pass123
            MYSQL_DATABASE: wordpress
            MYSQL_USER: testuser
            MYSQL_PASSWORD: pass123
        networks:
            - sw-br-networks
# wordpress servisi
    wordpress:
        depends_on:
            - db
        image: wordpress:latest
        ports:
            - "8080:80"
        restart: always
        volumes:
            - /var/www/html
        environment:
            WORDPRESS_DB_HOST: Db:3306
            WORDPRESS_DB_USER: testuser
            WORDPRESS_DB_PASSWORD: pass123
        networks:
            - sw-br-networks
# phpMyAdmin servisi
    phpmyadmin:
        depends_on:
            - db
        image: phpmyadmin/phpmyadmin
        restart: always
        ports: 
            - "7080:80"
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: pass123
        networks:
            - sw-br-networks
# Network ve Volume Tanımı        
networks:
    sw-br-networks:
volumes:
    db_data: